# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [55]:
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

In [56]:
import pandas as pd

In [57]:
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)

In [58]:
df1.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [59]:
df2.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='str')

In [60]:
df3.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='str')

In [61]:
df1.columns = [column.lower().replace(" ","_")for column in df1.columns]
df2.columns = [column.lower().replace(" ","_")for column in df2.columns]
df3.columns = [column.lower().replace(" ","_")for column in df3.columns]

In [62]:
df2 = df2.rename(columns={"st": "state"})
df1 = df1.rename(columns={"st": "state"})

In [63]:
company_df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

In [64]:
company_df.shape

(12074, 11)

In [65]:
company_df.isna().sum()

customer                     2937
state                        2937
gender                       3059
education                    2937
customer_lifetime_value      2944
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [66]:
company_df = company_df.dropna(how="all")
company_df.isna().sum()

customer                       0
state                          0
gender                       122
education                      0
customer_lifetime_value        7
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [67]:
company_df["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

In [68]:
company_df["gender"] = company_df["gender"].replace({"Femal" : "F", "female" : "F", "Male":"M"})

In [69]:
company_df["gender"] = company_df["gender"].fillna("Unknown")

In [70]:
company_df["gender"].unique()

<ArrowStringArray>
['Unknown', 'F', 'M']
Length: 3, dtype: str

In [71]:
company_df["customer_lifetime_value"].dtype

dtype('O')

In [72]:
company_df["customer_lifetime_value"].head(10)

0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
5     825629.78%
6     538089.86%
7     721610.03%
8    2412750.40%
9     738817.81%
Name: customer_lifetime_value, dtype: object

In [73]:
print(df1["customer_lifetime_value"].head(3))
print(df2["customer_lifetime_value"].head(3))
print(df3["customer_lifetime_value"].head(3))

0            NaN
1     697953.59%
2    1288743.17%
Name: customer_lifetime_value, dtype: str
0    323912.47%
1    462680.11%
2    899704.02%
Name: customer_lifetime_value, dtype: str
0    3479.137523
1    2502.637401
2    3265.156348
Name: customer_lifetime_value, dtype: float64

In [74]:
def clean_clv(value):
    if isinstance(value, str):
        value = value.replace("%", "")
        return float(value) / 100
    else:
        return value

In [75]:
company_df["customer_lifetime_value"] = company_df["customer_lifetime_value"].apply(clean_clv)

In [76]:
print(company_df["customer_lifetime_value"].head())
print(company_df["customer_lifetime_value"].dtype)

0           NaN
1     6979.5359
2    12887.4317
3     7645.8618
4     5363.0765
Name: customer_lifetime_value, dtype: float64
float64

In [77]:
clv_median = company_df["customer_lifetime_value"].median()

In [78]:
company_df["customer_lifetime_value"] = company_df["customer_lifetime_value"].fillna(clv_median)

In [79]:
company_df["customer_lifetime_value"].isna().sum()

np.int64(0)

In [80]:
company_df["state"].unique()

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali', 'AZ',
 'WA']
Length: 8, dtype: str

In [81]:
company_df["state"] = company_df["state"].replace({"Cali" : "California", "AZ" : "Arizona", "WA":"Washington"})

In [82]:
company_df["state"].unique()

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon']
Length: 5, dtype: str

In [83]:
company_df["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Bachelors',
 'Doctor']
Length: 6, dtype: str

In [84]:
company_df["education"] = company_df["education"].replace({"Bachelors" : "Bachelor"})

In [85]:
company_df["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor']
Length: 5, dtype: str

In [88]:
def clean_complaints(value):
    if isinstance(value, str):
        if "/" in value:
            parts = value.split("/")
            return int(parts[1])
        else:
            return int(value)
    else:
        return int(value)


company_df["number_of_open_complaints"] = (company_df["number_of_open_complaints"].apply(clean_complaints))

company_df["number_of_open_complaints"].unique()

array([0, 2, 1, 3, 5, 4])

In [89]:
print(company_df["policy_type"].unique())
print(company_df["vehicle_class"].unique())

<ArrowStringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: str
<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car']
Length: 6, dtype: str

In [ ]:
numeric_columns = ["customer_lifetime_value","income","monthly_premium_auto","total_claim_amount"]

for column in numeric_columns:
    company_df[column] = company_df[column].astype(float)

company_df.dtypes

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [91]:
company_df.select_dtypes(include="number").describe()

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
count,9137.000000,9137.000000,9137.000000,9137.000000,9137.000000
mean,7975.362794,37828.820291,110.391266,0.383715,430.527140
std,6807.016801,30358.716159,581.376032,0.908988,289.582968
min,1898.007675,0.000000,61.000000,0.000000,0.099007
25%,3981.775889,0.000000,68.000000,0.000000,266.996814
50%,5764.716400,34244.000000,83.000000,0.000000,377.561463
75%,8929.611119,62447.000000,109.000000,0.000000,546.420009
max,83325.381190,99981.000000,35354.000000,5.000000,2893.239678

In [ ]:
company_df.sort_values("monthly_premium_auto",ascending=False).head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
44,YD87931,Washington,M,Doctor,4951.6561,46896.0,35354.0,1,Personal Auto,Four-Door Car,31.707317
856,QZ77637,Washington,F,College,11665.0978,84978.0,35353.0,1,Corporate Auto,Four-Door Car,166.772960
747,JT11876,Washington,F,High School or Below,5435.7678,0.0,10202.0,0,Personal Auto,Four-Door Car,626.116259
4616,MP96373,Washington,M,Master,5719.7857,54585.0,7575.0,1,Personal Auto,Two-Door Car,340.800000
4283,KN13494,Washington,F,Master,5181.6209,97131.0,6464.0,0,Personal Auto,Four-Door Car,307.200000
4265,XR95069,Washington,Unknown,Bachelor,4854.7457,29834.0,6464.0,0,Personal Auto,Four-Door Car,307.200000
114,SG20925,Washington,F,Master,5185.7976,99428.0,6464.0,1,Personal Auto,Four-Door Car,48.046869
4275,VW82067,Washington,F,Master,5181.6209,97131.0,6464.0,0,Personal Auto,Four-Door Car,307.200000
354,CI38330,Washington,M,Bachelor,2549.7861,72217.0,6464.0,0,Personal Auto,Four-Door Car,91.146661
4066,UB16654,Washington,M,Master,4718.5585,15680.0,6464.0,0,Personal Auto,Four-Door Car,260.879903

In [93]:
print("Duplicados antes:", company_df.duplicated().sum())

company_df = company_df.drop_duplicates()
company_df = company_df.reset_index(drop=True)

print("Duplicados después:", company_df.duplicated().sum())
print("Filas y columnas:", company_df.shape)

Duplicados antes: 3
Duplicados después: 0
Filas y columnas: (9134, 11)

In [94]:
print("Valores nulos:")
print(company_df.isna().sum())

print("\nTipos de datos:")
print(company_df.dtypes)

Valores nulos:
customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

Tipos de datos:
customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      int64
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

In [95]:
company_df.to_csv("company_combined_clean.csv", index=False)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [96]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

In [97]:
import pandas as pd

In [100]:
marketing_df = pd.read_csv(url)
marketing_df.head(5)
marketing_df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='str')

In [101]:
revenue_by_channel = marketing_df.pivot_table(index="sales_channel",values="monthly_premium_auto",aggfunc="sum").round(2)

revenue_by_channel

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

In [104]:
clv_by_gender_education = marketing_df.pivot_table(index="gender",columns="education", values="customer_lifetime_value",aggfunc="mean").round(2)
clv_by_gender_education

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [105]:
complaints_by_policy_month = marketing_df.groupby(["policy_type", "month"])["number_of_open_complaints"].sum().reset_index()

complaints_by_policy_month

      policy_type  month  number_of_open_complaints
0  Corporate Auto      1                 443.434952
1  Corporate Auto      2                 385.208135
2   Personal Auto      1                1727.605722
3   Personal Auto      2                1453.684441
4    Special Auto      1                  87.074049
5    Special Auto      2                  95.226817

In [106]:
marketing_df["number_of_open_complaints"].unique()

array([0.        , 0.38425611, 3.        , 1.        , 2.        ,
       4.        , 5.        ])

In [107]:
complaints_by_policy_month = complaints_by_policy_month.round(2)
complaints_by_policy_month

      policy_type  month  number_of_open_complaints
0  Corporate Auto      1                     443.43
1  Corporate Auto      2                     385.21
2   Personal Auto      1                    1727.61
3   Personal Auto      2                    1453.68
4    Special Auto      1                      87.07
5    Special Auto      2                      95.23